[package]
name = "echo"
version.workspace = true
edition.workspace = true
description = "Echo tool - proof of concept"
license.workspace = true

[[bin]]
name = "echo"
path = "src/main.rs"

[dependencies]
bitter-sdk = { path = "../../bitter-sdk" }
anyhow.workspace = true
